references:
  envoy-build-image: &envoy-build-image
    envoyproxy/envoy-build-ubuntu@sha256:3ca8acc35fdb57ab26e1bb5f9488f37095f45acd77a12602510410dbefa00b58 # October 30th, 2019
version: 2
jobs:
  build:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh build
  test:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh test
  clang_tidy:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh clang_tidy
  test_with_valgrind:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh test_with_valgrind
  coverage:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh coverage
      - store_artifacts:
          path: /root/project/generated
          destination: /
  asan:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh asan
  tsan:
    docker:
      - image: *envoy-build-image
    resource_class: xlarge
    steps:
      - checkout
      - run: ci/do_ci.sh tsan
  format:
    docker:
      - image: *envoy-build-image
    resource_class: small
    steps:
      - checkout
      - run: ci/do_ci.sh check_format

workflows:
  version: 2
  all:
    jobs:
      - build
      - test
      - clang_tidy
#      - test_with_valgrind
      - coverage
      - asan
      - tsan
      - format
